import {
	Briefcase,
	ChartColumn,
	FileText,
	Handshake,
	Mail,
	Receipt,
	Rocket,
	Route,
	Settings,
	Smartphone,
	Sparkles,
	Users,
	Zap,
} from "lucide-react";
import type { HelpCategoryMeta } from "./types";

export const HELP_CATEGORY_META: HelpCategoryMeta[] = [
	{
		slug: "getting-started",
		name: "Getting started",
		description: "Set up your organization and run your first job in OneTool.",
		icon: Rocket,
		group: "start",
		ordered: true,
	},
	{
		slug: "clients",
		name: "Clients",
		description: "Keep every customer, contact, and service address in one place.",
		icon: Users,
		group: "features",
	},
	{
		slug: "projects-and-tasks",
		name: "Projects and tasks",
		description: "Plan the work, schedule it, and assign it to your team.",
		icon: Briefcase,
		group: "features",
	},
	{
		slug: "quotes",
		name: "Quotes and e-signatures",
		description: "Send priced proposals your clients can approve and sign online.",
		icon: FileText,
		group: "features",
	},
	{
		slug: "invoices-and-payments",
		name: "Invoices and payments",
		description: "Bill for finished work and collect payment by card, cash, or check.",
		icon: Receipt,
		group: "features",
	},
	{
		slug: "client-portal",
		name: "Client portal",
		description: "The branded site where your clients approve quotes and pay invoices.",
		icon: Handshake,
		group: "features",
	},
	{
		slug: "inbox",
		name: "Email inbox",
		description: "A shared inbox for every email between your team and your clients.",
		icon: Mail,
		group: "features",
	},
	{
		slug: "automations",
		name: "Automations",
		description: "Build workflows that react to changes in your business automatically.",
		icon: Zap,
		group: "features",
	},
	{
		slug: "ai-assistant",
		name: "AI assistant",
		description: "Ask questions about your business and get work done in chat.",
		icon: Sparkles,
		group: "features",
	},
	{
		slug: "routing",
		name: "Routing",
		description: "Turn a list of stops into an efficient driving route for the day.",
		icon: Route,
		group: "features",
	},
	{
		slug: "reports",
		name: "Reports",
		description: "Build and save custom views of your clients, jobs, and revenue.",
		icon: ChartColumn,
		group: "features",
	},
	{
		slug: "settings-and-team",
		name: "Settings and team",
		description: "Branding, billing, payments setup, and who can access what.",
		icon: Settings,
		group: "features",
	},
	{
		slug: "mobile-app",
		name: "Mobile app",
		description: "Take OneTool into the field with the iPhone and iPad companion app.",
		icon: Smartphone,
		group: "features",
	},
];
